pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
  - dev
  - /renovate\/.*/
skip_tags: true
max_jobs: 1
skip_commits:
 files:
   - README.md
   - CHANGELOG.md
   - .editorconfig
   - .gitignore

environment:
  TestTimeout: 30000

image:
  - Visual Studio 2017
  - Ubuntu1804

cache:
  - '%USERPROFILE%\.nuget\packages -> **\*.csproj, **\Directory.Build.props, **\Directory.Build.targets'
  - '~/.nuget/packages -> **\*.csproj, **\Directory.Build.props, **\Directory.Build.targets'

init:
  - git config --global core.autocrlf true

nuget:
  account_feed: false
  project_feed: false
  disable_publish_on_pr: true

configuration: Release

before_build:
  - dotnet --version

build:
  verbosity: minimal
  project: EPPlus.Core.sln
  publish_nuget: false
  publish_nuget_symbols: false

# test:
#   assemblies:
#     only:
#       - 'EPPlusTest\bin\**\EPPlusTest.dll'

test_script:
  - ps: $ErrorActionPreference = 'SilentlyContinue'; dotnet test EPPlusTest/EPPlusTest.Core.csproj -c $($env:CONFIGURATION) --no-build --test-adapter-path:. --logger:Appveyor -- MSTestV2.TestTimeout=$($env:TestTimeout)

for:
-
  matrix:
    only:
      - image: Visual Studio 2017
  build:
    publish_nuget: true
  before_build:
    - dotnet restore EPPlus.Core.sln
  # test_script:
  #   - ps: dotnet test EPPlusTest/EPPlusTest.Core.csproj -c $env:configuration --no-build -l Appveyor -- MSTestV2.TestTimeout=15000

