pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
  - dev
skip_tags: true
max_jobs: 1
skip_commits:
 files:
   - README.md
   - CHANGELOG.md
   - .editorconfig
   - .gitignore

environment:
  TestTimeout: 30000

image:
  - Visual Studio 2017
  - ubuntu1804

cache:
  - '%USERPROFILE%\.nuget\packages -> **\*.csproj, **\Directory.Build.props, **\Directory.Build.targets'

init:
  - git config --global core.autocrlf true

nuget:
  account_feed: false
  project_feed: true
  disable_publish_on_pr: true

configuration: Release

before_build:
  - dotnet --version

build:
  verbosity: minimal
  project: EPPlus.Core.sln
  publish_nuget: false
  publish_nuget_symbols: false

# test:
#   assemblies:
#     only:
#       - 'EPPlusTest\bin\**\EPPlusTest.dll'

test_script:
  - ps: dotnet test EPPlusTest/EPPlusTest.Core.csproj -c $env:configuration --no-build -l "trx:LogFileName=results.trx" -v n -- MSTestV2.TestTimeout=$($env:TestTimeout)
  - ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/mstest/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\results.xml));

for:
-
  matrix:
    only:
      - image: Visual Studio 2017
  build:
    publish_nuget: true
  before_build:
    - dotnet restore --verbosity m EPPlus.Core.sln
  # test_script:
  #   - ps: dotnet test EPPlusTest/EPPlusTest.Core.csproj -c $env:configuration --no-build -l Appveyor -- MSTestV2.TestTimeout=15000
-
  matrix:
    only:
      - image: ubuntu1804

