comment: false
codecov:
  require_ci_to_pass: false
  notify:
    after_n_builds: 3
    wait_for_ci: true
coverage:
  status:
    project:
      default:
        # flaky tests
        threshold: 0.5%
