name: build

on:
  push:

env:
  CONFIGURATION: Release
  DOTNET_NOLOGO: true # https://github.com/actions/setup-dotnet#environment-variables-to-use-with-dotnet

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # renovate: tag=v2.3.4

      - uses: actions/cache@c64c572235d810460d0d6876e9c705ad5002b353 # renovate: tag=v2.1.6
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/*.props') }}

      - name: restore packages
        run: dotnet restore EPPlusTest/EPPlusTest.Core.csproj

      - name: build
        run: dotnet build EPPlusTest/EPPlusTest.Core.csproj --no-restore

      - name: test
        run: dotnet test EPPlusTest/EPPlusTest.Core.csproj --no-build --collect:"XPlat Code Coverage" --settings EPPlusTest.runsettings

      - name: Codecov
        uses: codecov/codecov-action@5a8bb4701eca7ba3673f21664b887f652c58d0a3 # renovate: tag=v2.0.3
        if: always()

  publish:
    runs-on: windows-latest
    needs: test

    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # renovate: tag=v2.3.4
        with:
          fetch-depth: 0

      - uses: actions/cache@c64c572235d810460d0d6876e9c705ad5002b353 # renovate: tag=v2.1.6
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/*.props') }}

      - name: restore packages
        run: dotnet restore EPPlus/EPPlus.MultiTarget.csproj

      - name: build
        run: dotnet build EPPlus/EPPlus.MultiTarget.csproj --no-restore

      - name: pack
        run: dotnet pack EPPlus/EPPlus.MultiTarget.csproj --no-build

      - name: publish to github
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          dotnet nuget push *.nupkg \
            -s https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json \
            -k ${{ secrets.GITHUB_TOKEN }} \
            --skip-duplicate
        working-directory: EPPlus/bin/${{ env.CONFIGURATION }}
        shell: bash

      - name: publish to nuget
        if: startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, '-')
        run: |
          dotnet nuget push *.nupkg \
            -s nuget.org \
            -k ${{ secrets.NUGET_API_KEY }} \
            --skip-duplicate
        working-directory: EPPlus/bin/${{ env.CONFIGURATION }}
        shell: bash
